name: Test Secrets in Environments

on:
  push:
    branches:
      - dev
      
      - qa
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables based on branch
        id: set_env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "ENV_NAME=dev" >> $GITHUB_ENV
            echo "SECRET_KEY=SECRET_KEY_DEV" >> $GITHUB_ENV
            echo "API_KEY=API_KEY_DEV" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/qa" ]]; then
            echo "ENV_NAME=qa" >> $GITHUB_ENV
            echo "SECRET_KEY=SECRET_KEY_QA" >> $GITHUB_ENV
            echo "API_KEY=API_KEY_QA" >> $GITHUB_ENV
          else
            echo "ENV_NAME=prod" >> $GITHUB_ENV
            echo "SECRET_KEY=SECRET_KEY_PROD" >> $GITHUB_ENV
            echo "API_KEY=API_KEY_PROD" >> $GITHUB_ENV
          fi

      - name: Print secrets based on environment
        run: |
          echo "Running in the ${{ env.ENV_NAME }} environment"
          echo "SECRET_KEY: ${{ secrets[env.SECRET_KEY_PROD] }}"
          echo "API_KEY: ${{ secrets[env.API_KEY_PROD] }}"
