name: Test Secrets in Environments

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs: # hola
  test-secrets:
    runs-on: ubuntu-latest
    environment:
      # The environment name depends on the branch that is pushed
      # dev -> dev environment
      # qa -> qa environment
      # main -> prod environment
      name: ${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/qa' && 'qa' || 'prod' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print secrets based on environment
        run: |
          echo "Running in the ${{ environment.name }} environment"
          echo "SECRET_KEY: ${{ secrets["SECRET_KEY_${{ environment.name | upper }}"] }}"
          echo "API_KEY: ${{ secrets["API_KEY_${{ environment.name | upper }}"] }}"
